# Based on https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# Removed docker image caching for simplicity.

version: 2
jobs:
  docker-build:
    working_directory: /rails-template
    docker:
      # From https://registry.hub.docker.com/_/docker/tags
      - image: docker:20.10.21-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run test
          command: |
            ./test-docker.sh

workflows:
  version: 2
  parallel-docker-rails:
    jobs:
      - docker-build
      # TODO: rails